### ISSUE TITLE
Cannot use from interactive node shell

### ISSUE THREAD

**Issue by bsyk** [octet-stream/node-yaml#3]
Trying to use node-yaml from within an interactive node shell the following error occurs:
```
TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at dirname (path.js:1345:5)
    at Object.<anonymous> (/Users/xxx/node_modules/node-yaml/main.js:28:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```

Which points to this line, as there is no parent module requiring this module.
``PARENT_DIRNAME = dirname(module.parent.filename);``

Steps to reproduce:

1. ``npm install --no-save --production node-yaml``
1. ``node``
1. ``> yml = require('node-yaml')``
```
TypeError: Path must be a string. Received null
    ...
```

**Comment by octet-stream** [comment]
Hello! Thanks for your report. It's already fixed in 3.1.1, try to upgrade node-yaml.
